config/routes.rb
Mypigapp::Application.routes.draw do
  resources :healths
  resources :slaughters
  resources :litters
  resources :pigs

  
  match "/" => "home#index", as: :home

end

app/models/pig.rb
class Pig < ActiveRecord::Base
  attr_accessible :name, :dob, :status, :slaughter_id, :litter
  validates_presence_of :dob, :name, :status

  belongs_to :slaughter
  belongs_to :litter
  
  def health
    Health.find(self.status).name
  end
  
  def age_in_days
    ((Time.now - self.dob) / (3600 * 24)).to_i
  end
  
  def age_in_weeks
    (self.age_in_days / 7).to_i
  end
  
  def age
    if self.age_in_days < 1
      "Born today!"
    elsif self.age_in_days < 14
      self.age_in_days.to_s + " days"
    else
      self.age_in_weeks.to_s + " weeks"
    end
  end
end

app/controllers/pigs_controller.rb
class PigsController < ApplicationController
  # GET /pigs
  # GET /pigs.json
  def index
    @pigs = Pig.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pigs }
    end
  end

  # GET /pigs/1
  # GET /pigs/1.json
  def show
    @pig = Pig.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pig }
    end
  end

  # GET /pigs/new
  # GET /pigs/new.json
  def new
    @pig = Pig.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pig }
    end
  end

  # GET /pigs/1/edit
  def edit
    @pig = Pig.find(params[:id])
  end

  # POST /pigs
  # POST /pigs.json
  def create
    @pig = Pig.new(params[:pig])

    respond_to do |format|
      if @pig.save
        format.html { redirect_to @pig, notice: 'Pig was successfully created.' }
        format.json { render json: @pig, status: :created, location: @pig }
      else
        format.html { render action: "new" }
        format.json { render json: @pig.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pigs/1
  # PUT /pigs/1.json
  def update
    @pig = Pig.find(params[:id])

    respond_to do |format|
      if @pig.update_attributes(params[:pig])
        format.html { redirect_to @pig, notice: 'Pig was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pig.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pigs/1
  # DELETE /pigs/1.json
  def destroy
    @pig = Pig.find(params[:id])
    @pig.destroy

    respond_to do |format|
      format.html { redirect_to pigs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/pigs_helper.rb
module PigsHelper
end

app/views/pigs/_form.html.erb
<%= simple_form_for(@pig, :html => {:class => 'form-horizontal' }) do |f| %>
  
  <%= f.input :name %>

  <%= f.input :dob, as: :date, :order => [:day, :month, :year] %>
    
  <%= f.hidden_field :status, value: alive_id %>

  <div class="form-actions">
    <%= f.submit nil, class: "btn" %>
  </div>
<% end %>

app/views/pigs/edit.html.erb
<h1>Editing pig</h1>

<%= render 'form' %>

<%= link_to 'Show', @pig %> |
<%= link_to 'Back', pigs_path %>

app/views/pigs/index.html.erb
<h1>All <%= pluralize(@pigs.count, "pig") %></h1>

<table class="table">
  <tr>
    <th>Name</th>
    <th>Age</th>
    <th>Status</th>
    <th>Litter</th>
    <th></th>
    <th></th>
  </tr>

<% @pigs.each do |pig| %>
  <tr>
    <td><%= link_to pig.name, pig %></td>
    <td><%= pig.age %></td>
    <td><%= pig.health %></td>
    <td><%= pig.litter.name unless pig.litter.nil? %></td>
    <td><%= link_to 'Edit', edit_pig_path(pig) %></td>
    <td><%= link_to 'Delete', pig, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Pig', new_pig_path %>

app/views/pigs/new.html.erb
<h1>New pig</h1>

<%= render 'form' %>

<%= link_to 'Back', pigs_path %>

app/views/pigs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @pig.name %>
</p>

<p>
  <b>Age:</b>
  <%= @pig.age %>
</p>

<p>
  <b>Health:</b>
  <%= @pig.health %>
</p>


<%= link_to 'Edit', edit_pig_path(@pig) %> |
<%= link_to 'Back', pigs_path %>