config/routes.rb
Mypigapp::Application.routes.draw do
  resources :healths
  resources :slaughters
  resources :litters
  resources :pigs

  
  match "/" => "home#index", as: :home

end

app/models/health.rb
class Health < ActiveRecord::Base
  attr_accessible :name
end

app/controllers/healths_controller.rb
class HealthsController < ApplicationController
  # GET /healths
  # GET /healths.json
  def index
    @healths = Health.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @healths }
    end
  end

  # GET /healths/1
  # GET /healths/1.json
  def show
    @health = Health.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @health }
    end
  end

  # GET /healths/new
  # GET /healths/new.json
  def new
    @health = Health.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @health }
    end
  end

  # GET /healths/1/edit
  def edit
    @health = Health.find(params[:id])
  end

  # POST /healths
  # POST /healths.json
  def create
    @health = Health.new(params[:health])

    respond_to do |format|
      if @health.save
        format.html { redirect_to @health, notice: 'Health was successfully created.' }
        format.json { render json: @health, status: :created, location: @health }
      else
        format.html { render action: "new" }
        format.json { render json: @health.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /healths/1
  # PUT /healths/1.json
  def update
    @health = Health.find(params[:id])

    respond_to do |format|
      if @health.update_attributes(params[:health])
        format.html { redirect_to @health, notice: 'Health was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @health.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /healths/1
  # DELETE /healths/1.json
  def destroy
    @health = Health.find(params[:id])
    @health.destroy

    respond_to do |format|
      format.html { redirect_to healths_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/healths_helper.rb
module HealthsHelper
end

app/views/healths/_form.html.erb
<%= form_for(@health) do |f| %>
  <% if @health.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@health.errors.count, "error") %> prohibited this health from being saved:</h2>

      <ul>
      <% @health.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/healths/edit.html.erb
<h1>Editing health</h1>

<%= render 'form' %>

<%= link_to 'Show', @health %> |
<%= link_to 'Back', healths_path %>

app/views/healths/index.html.erb
<h1>Listing healths</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @healths.each do |health| %>
  <tr>
    <td><%= health.name %></td>
    <td><%= link_to 'Show', health %></td>
    <td><%= link_to 'Edit', edit_health_path(health) %></td>
    <td><%= link_to 'Destroy', health, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Health', new_health_path %>

app/views/healths/new.html.erb
<h1>New health</h1>

<%= render 'form' %>

<%= link_to 'Back', healths_path %>

app/views/healths/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @health.name %>
</p>


<%= link_to 'Edit', edit_health_path(@health) %> |
<%= link_to 'Back', healths_path %>