config/routes.rb
Mypigapp::Application.routes.draw do
  resources :healths
  resources :slaughters
  resources :litters
  resources :pigs

  
  match "/" => "home#index", as: :home

end

app/models/litter.rb
class Litter < ActiveRecord::Base
  attr_accessible :name, :sow_id
    
  has_many :pigs
  
  def sow
    Pig.find(self.sow_id)
  end
  
  def no_of_piglets
    self.pigs.count
  end
  
end

app/controllers/litters_controller.rb
class LittersController < ApplicationController
  
  include ApplicationHelper
  
  # GET /litters
  # GET /litters.json
  def index
    @litters = Litter.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @litters }
    end
  end

  # GET /litters/1
  # GET /litters/1.json
  def show
    @litter = Litter.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @litter }
    end
  end

  # GET /litters/new
  # GET /litters/new.json
  def new
    @litter = Litter.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @litter }
    end
  end

  # GET /litters/1/edit
  def edit
    @litter = Litter.find(params[:id])
  end

  # POST /litters
  # POST /litters.json
  def create
    @litter = Litter.new(params[:litter])
    @pig = Pig.find(@litter.sow_id)
    @no_of_piglets = params[:no_of_piglets].to_i
    
    @no_of_piglets.times do
      Pig.create(name: @pig.name + ' piglet', status: alive_id, dob: Time.now, litter: @litter)
    end

    respond_to do |format|
      if @litter.save
        format.html { redirect_to @litter, notice: 'Litter was successfully created with ' + @no_of_piglets.to_s + ' piglets' }
        format.json { render json: @litter, status: :created, location: @litter }
      else
        format.html { render action: "new" }
        format.json { render json: @litter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /litters/1
  # PUT /litters/1.json
  def update
    @litter = Litter.find(params[:id])

    respond_to do |format|
      if @litter.update_attributes(params[:litter])
        format.html { redirect_to @litter, notice: 'Litter was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @litter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /litters/1
  # DELETE /litters/1.json
  def destroy
    @litter = Litter.find(params[:id])
    @litter.destroy

    respond_to do |format|
      format.html { redirect_to litters_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/litters_helper.rb
module LittersHelper
end

app/views/litters/_form.html.erb
<%= simple_form_for(@litter, html: { class: "form-horizontal" }) do |f| %>

  <%= f.input :name %>
  
  <%= f.input :sow_id, collection: Pig.all, value_method: :id, label_method: :name %>
  
  <div class="control-group">
    <label class="control-label" for="">No. of piglets</label>
    <div class="controls">
      <%= number_field_tag 'no_of_piglets', nil, :in => 1...20 %>
    </div>
  </div>
  
  <div class="form-actions">
    <%= f.submit nil, class: "btn btn-success" %>
  </div>
  
<% end %>

app/views/litters/edit.html.erb
<h1>Editing litter</h1>

<%= render 'form' %>

<%= link_to 'Show', @litter %> |
<%= link_to 'Back', litters_path %>

app/views/litters/index.html.erb
<h1>Listing litters</h1>

<table class="table">
  <tr>
    <th>Name</th>
    <th>Sow</th>
    <th>No of piglets</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @litters.each do |litter| %>
  <tr>
    <td><%= link_to litter.name, litter %></td>
    <td><%= litter.sow.name %></td>
    <td><%= litter.no_of_piglets %>
    <td><%= link_to 'Edit', edit_litter_path(litter) %></td>
    <td><%= link_to 'Delete', litter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Litter', new_litter_path %>

app/views/litters/new.html.erb
<h1>New litter</h1>

<%= render 'form' %>

<%= link_to 'Back', litters_path %>

app/views/litters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @litter.name %>
</p>

<p>
  <b>Sow:</b>
  <%= @litter.sow.name %>
</p>

<h2>Piglets</h2>

<ul>
<% for piglet in @litter.pigs %>
  <li><%= piglet.name %></li>
<% end %>
</ul>

<%= link_to 'Edit', edit_litter_path(@litter) %> |
<%= link_to 'Back', litters_path %>