config/routes.rb
Mypigapp::Application.routes.draw do
  resources :healths
  resources :slaughters
  resources :litters
  resources :pigs

  
  match "/" => "home#index", as: :home

end

app/models/litter.rb
class Litter < ActiveRecord::Base
  attr_accessible :name, :sow_id
    
  has_many :pigs
  
  def sow
    Pig.find(self.sow_id)
  end
  
  def no_of_piglets
    self.pigs.count
  end
  
end

app/models/slaughter.rb
class Slaughter < ActiveRecord::Base
  attr_accessible :butcher_id, :transport_id, :pig_ids
  has_many :pigs
  after_create :kill_pigs
  
  include ApplicationHelper
  
  def kill_pigs
    pigs.each do |pig|
      pig.update_attributes(status: slaughtered_id)
    end
  end
end

app/controllers/slaughters_controller.rb
class SlaughtersController < ApplicationController
  # GET /slaughters
  # GET /slaughters.json
  def index
    @slaughters = Slaughter.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @slaughters }
    end
  end

  # GET /slaughters/1
  # GET /slaughters/1.json
  def show
    @slaughter = Slaughter.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @slaughter }
    end
  end

  # GET /slaughters/new
  # GET /slaughters/new.json
  def new
    @slaughter = Slaughter.new
    @pigs = Pig.where(slaughter_id: nil)

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @slaughter }
    end
  end

  # GET /slaughters/1/edit
  def edit
    @slaughter = Slaughter.find(params[:id])
    @pigs = Pig.where(slaughter_id: [nil, @slaughter.id])
  end

  # POST /slaughters
  # POST /slaughters.json
  def create
    @slaughter = Slaughter.new(params[:slaughter])

    respond_to do |format|
      if @slaughter.save
        format.html { redirect_to @slaughter, notice: 'Slaughter was successfully created.' }
        format.json { render json: @slaughter, status: :created, location: @slaughter }
      else
        format.html { render action: "new" }
        format.json { render json: @slaughter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /slaughters/1
  # PUT /slaughters/1.json
  def update
    @slaughter = Slaughter.find(params[:id])

    respond_to do |format|
      if @slaughter.update_attributes(params[:slaughter])
        format.html { redirect_to @slaughter, notice: 'Slaughter was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @slaughter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /slaughters/1
  # DELETE /slaughters/1.json
  def destroy
    @slaughter = Slaughter.find(params[:id])
    @slaughter.destroy

    respond_to do |format|
      format.html { redirect_to slaughters_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/slaughters_helper.rb
module SlaughtersHelper
end

app/views/slaughters/_form.html.erb
<hr>

<%= simple_form_for(@slaughter, html: { class: 'form-horizontal' }) do |f| %>

  <%= f.input :butcher_id %>

  <%= f.input :transport_id %>
  
  <div class="control-group">
    <label class="control-label">Pigs to be slaughtered</label>
    <div class="controls">
      <% @pigs.each do |pig| %>
        <%= hidden_field_tag "slaughter[pig_ids][]" %>
        <label class="checkbox">
          <%= check_box_tag "slaughter[pig_ids][]", pig.id, @slaughter.pigs.empty? ? false : @slaughter.pigs.include?(pig), :id => "slaughter_pig_ids_#{pig.id}" %>
          <%= pig.name %>
        </label>
      <% end %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, class: "btn btn-success" %>
  </div>
  
<% end %>

app/views/slaughters/edit.html.erb
<h1>Editing slaughter</h1>

<%= render 'form' %>

<%= link_to 'Show', @slaughter %> |
<%= link_to 'Back', slaughters_path %>

app/views/slaughters/index.html.erb
<h1>Listing slaughters</h1>

<table class="table">
  <tr>
    <th>Butcher</th>
    <th>Transport</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @slaughters.each do |slaughter| %>
  <tr>
    <td><%= slaughter.butcher_id %></td>
    <td><%= slaughter.transport_id %></td>
    <td><%= link_to 'Show', slaughter %></td>
    <td><%= link_to 'Edit', edit_slaughter_path(slaughter) %></td>
    <td><%= link_to 'Destroy', slaughter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Slaughter', new_slaughter_path %>

app/views/slaughters/new.html.erb
<h1>New slaughter</h1>

<%= render 'form' %>

<%= link_to 'Back', slaughters_path %>

app/views/slaughters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Butcher:</b>
  <%= @slaughter.butcher_id %>
</p>

<p>
  <b>Transport:</b>
  <%= @slaughter.transport_id %>
</p>

<h2>Dead pigs :(</h2>

<ul>
  <% for pig in @slaughter.pigs %>
    <li><%= pig.name %></li>
  <% end %>  
</ul>


<%= link_to 'Edit', edit_slaughter_path(@slaughter) %> |
<%= link_to 'Back', slaughters_path %>